// User roles
export const USER_ROLES = {
  ADMIN: 'ADMIN',
  SALES: 'SALES',
  WAREHOUSE: 'WAREHOUSE',
  QC: 'QC',
  REPAIR: 'REPAIR',
  VIEWER: 'VIEWER'
};

// Device statuses
export const DEVICE_STATUS = {
  IN_STOCK: 'IN_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  AWAITING_QC: 'AWAITING_QC',
  IN_QC: 'IN_QC',
  AWAITING_REPAIR: 'AWAITING_REPAIR',
  IN_REPAIR: 'IN_REPAIR',
  IN_LEVEL3: 'IN_LEVEL3',
  SHIPPED: 'SHIPPED',
  RETURNED: 'RETURNED',
  SCRAPPED: 'SCRAPPED'
};

// Purchase order statuses
export const PO_STATUS = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  FULLY_RECEIVED: 'FULLY_RECEIVED',
  CANCELLED: 'CANCELLED'
};

// Sales order statuses
export const SO_STATUS = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  PARTIALLY_SHIPPED: 'PARTIALLY_SHIPPED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

// Order types
export const ORDER_TYPE = {
  B2B: 'B2B',
  BACKMARKET: 'BACKMARKET'
};

// QC/Repair job statuses
export const JOB_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

// Repair statuses
export const REPAIR_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ESCALATED_L3: 'ESCALATED_L3',
  BER: 'BER'
};

// Level 3 repair statuses
export const L3_STATUS = {
  BOOKED_IN: 'BOOKED_IN',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_PARTS: 'AWAITING_PARTS',
  ON_HOLD: 'ON_HOLD',
  COMPLETED: 'COMPLETED',
  BER: 'BER',
  UNREPAIRABLE: 'UNREPAIRABLE'
};

// Couriers
export const COURIERS = {
  DPD: 'DPD',
  UPS: 'UPS',
  DHL: 'DHL',
  FEDEX: 'FEDEX',
  OTHER: 'OTHER'
};

// Admin operation types
export const ADMIN_OPERATIONS = {
  BULK_LOCATION_MOVE: 'BULK_LOCATION_MOVE',
  COLOR_CHECK: 'COLOR_CHECK',
  MANUAL_STATUS_CHANGE: 'MANUAL_STATUS_CHANGE',
  DATA_CORRECTION: 'DATA_CORRECTION',
  OTHER: 'OTHER'
};

// Event types for device history
export const EVENT_TYPE = {
  RECEIVED: 'RECEIVED',
  STATUS_CHANGE: 'STATUS_CHANGE',
  LOCATION_CHANGE: 'LOCATION_CHANGE',
  QC_COMPLETE: 'QC_COMPLETE',
  REPAIR_COMPLETE: 'REPAIR_COMPLETE',
  SHIPPED: 'SHIPPED',
  RETURNED: 'RETURNED',
  GRADE_CHANGE: 'GRADE_CHANGE',
  PROPERTY_UPDATE: 'PROPERTY_UPDATE',
  OTHER: 'OTHER'
};

// Grades
export const GRADES = ['A', 'B', 'C', 'D', 'E', 'F'];

// Storage options (GB)
export const STORAGE_OPTIONS = [8, 16, 32, 64, 128, 256, 512, 1024];
